// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://layzuwhfjrlyqifozayd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxheXp1d2hmanJseXFpZm96YXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTY1NjEsImV4cCI6MjA2OTk3MjU2MX0.MAixMdbY_RjzsGbU2Ziq-yRY_jkk1eZCM9wcbrnIDG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});